### ISSUE TITLE
Throws when included in the head of the document

### ISSUE THREAD

**Issue by rzane** [brianblakely/nodep-date-input-polyfill#1]
```
Cannot read property 'appendChild' of null
```

If it's a requirement that the user puts this at the bottom of the body, or if users should wait for DOMContentLoaded, it should probably at least be documented.

Nice work, btw. Nice to have a minimal polyfill for this.

**Comment by brianblakely** [comment]
Thanks a ton for your ticket, I'm sorry there has been no response until now!  Will address promptly.

**Comment by lulessa** [comment]
Also seeing this on Safari OS X. I have the polyfill bundled in a Rails application.js manifest (loaded in document head).

**Comment by ericcirone** [comment]
I'm still getting this issue. I have it placed in the HEAD of my page.

**Comment by rzane** [comment]
@ericcirone To avoid the error, put the script tag at the bottom of the body.

**Comment by brianblakely** [comment]
FYI, I'm starting work on this problem again.  It isn't a simple matter, but I think it can be resolved.

**Comment by brianblakely** [comment]
The latest version will now work when included in the <head>, and also with the async and defer script attributes.

https://www.npmjs.com/package/nodep-date-input-polyfill
