### ISSUE TITLE
Importing fails webpack build

### ISSUE THREAD

**Issue by ianmcnally** [brianblakely/nodep-date-input-polyfill#11]
Hey Brian,

Thanks for putting your time into this polyfill. Unlike many of the options out there, this project is straightforward and easy to use.

When I was integrating it into my build, via webpack, I am getting a Reference error `window is not defined` error when bundling. This is contrary to the README that says I can use it with webpack 😢 .

Is it working for you?

**Comment by brianblakely** [comment]
Thank you for your kind words!

It is working for me; all of my own projects use Webpack at the moment.

Firstly, make sure you're on the latest version (check the project's NPM page) and that all of your bundles are using it. Unfortunately, a broken build was sent out a few publishes ago, so you might have gotten snagged by it. 

Once that is confirmed, if it still isn't working, please paste or screenshot the error log in the dev console, as well as the block of code it links to. 

Cheers!

**Comment by ianmcnally** [comment]
I went to create a test case repo and realized it was an issue with some server rendering my project was doing. A plain webpack bundling succeeded. Ooops! Thanks for lending some advice.

**Comment by brianblakely** [comment]
Glad it all worked out. Thanks for the update.
