### ISSUE TITLE
Use the fields value if it exist

### ISSUE THREAD

**Issue by ay13** [brianblakely/nodep-date-input-polyfill#20]
I have an error when using the polyfill in Safari (probably other browsers as well but only looking in Safari). If the date input has a value on page load the polyfill ignores it. 

In my situate someone comes to the form to edit the info and the currently saved info is there for them to edit. if they do not touch the date inputs and hit save then empty date fields are saved and the default date is blown away.

**Comment by brianblakely** [comment]
How is the field data being populated?  Keep in mind that setAttribute will not change the underlying value.

**Comment by brianblakely** [comment]
Please comment if you are still experiencing this issue.  Closing for now.
