### ISSUE TITLE
Ability to unset the date

### ISSUE THREAD

**Issue by ra-hardy** [brianblakely/nodep-date-input-polyfill#25]
I'd like to be able to set a blank date, e.g

`dateElement.value = null;`

Looking at the spec at https://www.w3.org/TR/html5/forms.html#date-state-(type=date), it says "The value attribute, if specified and not empty, must have a value that is a valid date string", and "If the value of the element is not a valid date string, then set it to the empty string instead."  So, I think adding the extra  this.element.value = ``; above would fix that.

Code in input.js would be something like:

```
set: val=> {
   if(!/^\d{4}-\d{2}-\d{2}$/.test(val)) {
              this.element.polyfillValue = ``;
              this.element.value = ``;
              return;
            }
```

etc

**Comment by brianblakely** [comment]
This is a very good suggestion, thank you for the research as well.

**Comment by brianblakely** [comment]
Note that you can't set `value` recursively, but using setAttribute is valid.
