### ISSUE TITLE
locale en-GB doesn't work

### ISSUE THREAD

**Issue by iiiis** [brianblakely/nodep-date-input-polyfill#33]
getLocaleText() changes the locale to lower case which means that it won't match a key on the locales object.

Then, because 'en_en-US' appears before 'en-GB' in the keys, and the match checks against the first two characters, en_en-US is always returned if looking for 'en-GB'

**Comment by brianblakely** [comment]
The issue was a little more convoluted, but you were essentially on-track.

I was treating `Array.prototype.map` as though it was destructive, which it isn't.  I often make the same mistake with `String.prototype.replace`.
