### ISSUE TITLE
Chrome Native Date Picker Conflict

### ISSUE THREAD

**Issue by MattSidor** [brianblakely/nodep-date-input-polyfill#34]
When I test this in Chrome 55+, the native date picker overlaps with this script's version (depending on where I click in the input box), and only the native picker will let me choose a date.

![nodep-date-input-polyfill](https://cloud.githubusercontent.com/assets/6138182/22495270/badf27b6-e7f3-11e6-90a2-1a480efc7bce.gif)

Is this expected behavior? If so, do I need to detect the user's browser and only load this library if the browser is IE, Firefox, or Safari?

**Comment by deltragon** [comment]
same behaviour confirmed on android 5.1 webview/browser.
feature request to use [modernizr](https://github.com/Modernizr/Modernizr) to detect native datepickers?

**Comment by brianblakely** [comment]
It would appear that an update in Chrome broke [the native detection code](https://github.com/brianblakely/nodep-date-input-polyfill/blob/master/input.js#L136).

**Comment by brianblakely** [comment]
Thanks a lot for your report!

Your example case is the library's debug page.  In the HTML for that page, the library `<script>` is included with the `data-nodep-date-input-polyfill-debug` attribute, which makes the library ignore its [detection code](https://github.com/brianblakely/nodep-date-input-polyfill/blob/master/input.js#L146).

If you're just playing with the debug page, just remove that attr to see the true library behavior.

If you're including the library in your app, use [one of the methods described in the README](https://github.com/brianblakely/nodep-date-input-polyfill#install).

If there are any details I've missed, please comment and tell me!

**Comment by MattSidor** [comment]
Thanks very much @brianblakely
