### ISSUE TITLE
readonly value don't work

### ISSUE THREAD

**Issue by fabifabi** [brianblakely/nodep-date-input-polyfill#37]
code:
        <input type="date"  readonly/>

result: we can change the input !!!!

(bonus, i translated in french:
"fr":{days:["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"], months:["Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Decembre"], today:"Aujourd'hui", format:"D/M/Y"} )

**Comment by fabifabi** [comment]
line 155:
document.querySelectorAll('input[type="date"]:not([data-has-picker]):not([readonly])')

**Comment by brianblakely** [comment]
Thank you for your report and for researching an easy fix.
