### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by massimosala** [brianblakely/nodep-date-input-polyfill#38]
Brian, I am not able to create a pull request and I have just 2 minutes of time.
FYI, in Italy the week start with monday. I don't know if the control take care of this.
best regards, Sala

These are the data :
  'it_it-IT': {
    days: [
      `Dom`,
      `Lun`,
      `Mar`,
      `Mer`,
      `Gio`,
      `Ven`,
      `Sab`
    ],
    months: [
      `Gennaio`,
      `Febbraio`,
      `Marzo`,
      `Aprile`,
      `Maggio`,
      `Giugno`,
      `Luglio`,
      `Agosto`,
      `Settembre`,
      `Ottobre`,
      `Novembre`,
      `Dicembre`
    ],
    today: `Oggi`,
    format: `D/M/Y`
  }

**Comment by brianblakely** [comment]
Fixed in 4.8.0
