### ISSUE TITLE
Option to avoid inline <style>

### ISSUE THREAD

**Issue by colinrotherham** [brianblakely/nodep-date-input-polyfill#4]
Hi,

It doesn't appear to be possible to avoid the inline **\<style\>** append.

I'd like to move all styling into my own Sass build. Can the built-in one be turned off?

Thanks

**Comment by jcgertig** [comment]
doubt that this will be added since it is built to be stand alone

**Comment by colinrotherham** [comment]
No worries, I've used a different polyfill instead.

Thanks
