### ISSUE TITLE
date input, when posted as part of form content, has invalid date format (expecting ISO yyyy-MM-dd)

### ISSUE THREAD

**Issue by Andycharalambous** [brianblakely/nodep-date-input-polyfill#45]
When I use this on IE 11, I'm seeing that the form post data is different to other browsers that have a native support for the HTML 5 date input type - they post the date value as yyyy-MM-dd while this polyfill posts the value as MM/dd/YYYY. Is there some way to control this?

Thanks

e.g - element in IE 11

`<input name="PolicyStartDate" class="text-box single-line" id="PolicyStartDate" type="date" value="05/18/2017" data-has-picker="">`

Under Chrome/Opera/Edge:

`<input name="PolicyStartDate" class="text-box single-line" id="PolicyStartDate" type="date" value="2017-05-18" data-has-picker="">`

**Comment by brianblakely** [comment]
This aspect of the browser's behavior is not under our control, but there are workarounds.

When you access the `value` property of the polyfilled input element, it will give you the currently-selected date in yyyy-MM-dd format.  With that, you can do a number of things:

* Create your own `[FormData object](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects)`

* Send the data as a web service parameter

* Hook into the form's `submit` event and change the date field's `value` attribute on-the-fly (I think this will work, but I don't recall ever trying it out)

Sorry that this can't be handled for you, but it would be considered too invasive for the polyfill to attempt, and that would be worse than doing nothing.

**Comment by Andycharalambous** [comment]
Hi

Thanks for the response! Yes, I went down that route eventually - I totally
understand the reasoning.

One other thing though - and i've not had a chance to debug yet, on a UK
system (en_GB region/language) the date is displaying in the US format
instead of the UK format of dd/MM/yyyy.

Thanks
Andy

**Comment by brianblakely** [comment]
That was fixed, see #33

**Comment by Andycharalambous** [comment]
Misunderstanding on my part. Didn't notice that lang attribute had to be present for different locale. I assumed it was based on navigator.language. I forked the repo and implemented this tiny tweak due to necessity in the system I'm using this in. 

Thanks
