### ISSUE TITLE
Date value not change on Angular 

### ISSUE THREAD

**Issue by ggsalas** [brianblakely/nodep-date-input-polyfill#51]
Hi, I have installed nodep-date-input-polyfill on an angular app and works well but the date is not updated (from 2017-08-08 to 2017-08-28) I see that the input have a correctly updated value but on the browser is wrong:

![](https://i.imgur.com/5CCwLU9.png)

How I can solve this?

Thanks and best regards
--- 
I use Angular version 1.3.8

**Comment by stevenvachon** [comment]
There's [date-input-polyfill](https://npmjs.com/date-input-polyfill), which doesn't have this issue. It, however, has a separate issue with `DOMContentLoaded`, which I've created a [pull request](https://github.com/jcgertig/date-input-polyfill/pull/34) for. Until it's merged, you can include it in your project:

```json
"date-input-polyfill": "stevenvachon/date-input-polyfill#built"
```

**Comment by brianblakely** [comment]
For ng apps, there are bunch of datepickers that hook into Angular's plumbing.  [That fork](https://github.com/brianblakely/nodep-date-input-polyfill/issues/51#issuecomment-321143387) is not really a polyfill and isn't quite maintained, but I think it was made to adapt this project for things like Angular.
