### ISSUE TITLE
Date does not appear if you have previously deleted it manually

### ISSUE THREAD

**Issue by inkice-cd** [brianblakely/nodep-date-input-polyfill#55]
Hi! I have noticed that if you manually delete the date in the input (when all the text inside the input is deleted), after that, even if you select a specific date in the calendar, the date does not appear in the input... Is it a normal behavior or is it a bug? Awesome scripts, thanks a lot !!

**Comment by brianblakely** [comment]
This is a browser restriction. Once the user as typed in the field on their own, JavaScript cannot overwrite their manual input.

For more details, see the “Usage Notes” in the readme: https://github.com/brianblakely/nodep-date-input-polyfill/blob/master/README.md
