### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by rpopovici** [brianblakely/nodep-date-input-polyfill#56]
Hello guys,
Is this polyfill working on react managed input elements? I get to see the picker but value update in the field never happens when you pick a date

**Comment by rpopovici** [comment]
I tried the original project and html5-simple-date-input-polyfill and they both work as expected

**Comment by rpopovici** [comment]
Apparently the problem is in the value setter. If I remove it, then it's working

**Comment by RWOverdijk** [comment]
👍

**Comment by brianblakely** [comment]
There are datepicker React components.  This library is a drop-in for projects without strong dependencies.  Cheers!

**Comment by RWOverdijk** [comment]
Then don't call it a polyfill.

**Comment by brianblakely** [comment]
This solution polyfills native DOM APIs and provides a picker UI.

React is not a part of the Web Platform and any assumptions it makes are naturally tied to native behaviors per user agent, not a spec.
