### ISSUE TITLE
Popup behind other elements

### ISSUE THREAD

**Issue by TheDude70** [brianblakely/nodep-date-input-polyfill#7]
The date picker will fall behind another date field  that is placed below.

date_field1
date_field2
...

The popup for field one will fall behind field2.

**Comment by brianblakely** [comment]
By default, for the sake of flexibility, [all pickers have a z-index of 1](https://github.com/brianblakely/nodep-date-input-polyfill/blob/master/nodep-date-input-polyfill.scss).  You can override this in your app's own CSS, and you often will need to do so.

Give the pickers a sufficiently high z-index, and this issue will likely be resolved.

**Comment by CAYdenberg** [comment]
That only works with an !important declaration, however. It would be really useful to be able to set the z-index at initialization.

**Comment by japrogramer** [comment]
how would i overide the z-index? 
<input type='date' style="z-index: 1000 !important' /> ?
