### ISSUE TITLE
TypeError on focus

### ISSUE THREAD

**Issue by philsinatra** [brianblakely/nodep-date-input-polyfill#9]
There's a javascript error on focus of the input field.

```
TypeError: undefined is not an object (evaluating 'c.thePicker.attachTo')
```

This error is present regardless of browser. It exists in your package's index file.

![screen shot 2016-06-09 at 10 34 28 am](https://cloud.githubusercontent.com/assets/1465808/15933555/2e86c6c2-2e2e-11e6-82d1-65938cf9ee78.png)

**Comment by brianblakely** [comment]
To view that test case properly, you must follow the [Contributing Guide](https://github.com/brianblakely/nodep-date-input-polyfill#contributing).

Please feel free to follow up if this is happening in an actual project you're working on.
